title: counting-creatures
hero_image: images/banner.png
description: counting-creatures description
version: 4
listed: false
copyedit: false
last_tested: "2020-08-24"
steps:
  - title: Introduction
  - title: Detecting colours
  - title: More colours
  - title: Broadcasting colours
