title: Count the creatures
hero_image: images/banner.png
description: Create a wildlife camera that can count the number of birds of different colours that pass in front of the camera
version: 4
listed: false
copyedit: false
last_tested: "2020-08-24"
steps:
  - title: Introduction
  - title: Detect colours
  - title: More colours
  - title: Broadcast colours
  - title: Count colours
  - title: More animals
  - title: Share your project
  - title: What next?
